steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "northamerica-northeast2-docker.pkg.dev/microservices-project-471716/image-registry/orders.ms",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "northamerica-northeast2-docker.pkg.dev/microservices-project-471716/image-registry/orders.ms",
      ]
options:
  logging: CLOUD_LOGGING_ONLY